[[buttons]]
url = "https://large.horse/"
image = "/large-horse.gif"
alt = "large.horse"

[[buttons]]
url = "https://transrats.neocities.org/"
image = "/transrats.gif"
alt = "trans rats"

[[buttons]]
url = "https://cobra.monster/"
image = "/cobra-monster.webp"
alt = "cobra.monster"

[[buttons]]
image = "88x31.webp"
alt = "88 x 31"

[[buttons]]
image = "free-palestine.webp"
alt = "free palestine"

[[buttons]]
image = "graphic-design-passion.webp"
alt = "graphic design is my passion"

[[buttons]]
image = "puter-full-of-rats.webp"
alt = "'puter full of rats"

[[buttons]]
image = "queer-coded.webp"
alt = "queer coded"